#!/bin/bash
flutter analyze
dart format .
# Exit with a non-zero status if the checks fail to prevent the commit
if [ $? -ne 0 ]; then
  echo "Git hook failed due to analysis/formatting issues. Please fix them before committing."
  exit 1
fi
